spring.application.name=agendamento


# Banco Principal (Domínio)

spring.datasource.principal.jdbc-url=jdbc:h2:mem:base_principal
spring.datasource.principal.driver-class-name=org.h2.Driver
spring.datasource.principal.username=sa
spring.datasource.principal.password=

# Banco de Auditoria (Logs)

spring.datasource.auditoria.jdbc-url=jdbc:h2:mem:base_auditoria
spring.datasource.auditoria.driver-class-name=org.h2.Driver
spring.datasource.auditoria.username=sa
spring.datasource.auditoria.password=

# Cria as tabelas automaticamente baseado nas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Habilita a interface web do banco H2 (acesso via localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console